# Use root/example as user/password credentials
version: '3.8'
services:

  db:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: idle_resource_db
    ports:
      - "3306:3306"
    
    # (this is just an example, not intended to be a production configuration)
